# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171009_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedarticle',
            name='link',
            field=models.URLField(default='', max_length=255),
        ),
    ]
