# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_taggedarticle_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedarticle',
            name='link',
            field=models.URLField(max_length=255),
        ),
    ]
