# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-10 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171009_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggedarticle',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
