# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_taggedarticle_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedarticle',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
