application: brain
runtime: python
version: 1
api_version: 1
threadsafe: true
libraries:
- name: django
  version: "1.10.5"

runtime_config:
    python_version: 3

builtins:
- django_wsgi: on
handlers:
- url: .*
  script: brain/urls.py
