application: brain
runtime: python36
version: 1
api_version: 1
threadsafe: true
libraries:
- name: django
  version: "1.10.5"


builtins:
- django_wsgi: on
handlers:
- url: .*
  script: brain/urls.py
