# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-08 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20171008_0840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
