# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-08 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.IntegerField(choices=[(1, 'Acute Threat ("Fear")'), (2, 'Potential Threat ("Anxiety")'), (2, 'Sustained Threat'), (4, 'Loss'), (5, 'Frustrative Nonreward'), (6, 'Approach Motivation: Reward Valuation'), (7, 'Approach Motivation: Effort Valuation / Willingness to Work'), (8, 'Approach Motivation: Expectancy / Reward Prediction Error'), (9, 'Approach Motivation: Action Selection / Preference-Based Decision Making'), (10, 'Initial Responsiveness to Reward Attainment'), (11, 'Sustained/Longer-Term Responsiveness to Reward Attainment'), (12, 'Reward Learning'), (13, 'Habit'), (14, 'Attention'), (15, 'Perception'), (16, 'Declarative Memory'), (17, 'Language'), (18, 'Cognitive Control'), (19, 'Working Memory'), (20, 'Affiliation and Attachment'), (21, 'Social Communication'), (22, 'Perception and Understanding of Self: Agency'), (23, 'Perception and Understanding of Self: Self-Knowledge'), (24, 'Perceptions and Understanding of Others: Animacy Perception'), (25, 'Perceptions and Understanding of Others: Action Perception'), (26, 'Perceptions and Understanding of Others: Understanding Mental States'), (27, 'Arousal'), (28, 'Circadian Rhythms'), (29, 'Sleep-Wakefulness')]),
        ),
    ]
