# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-08 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20171008_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Acute Threat', 'Acute Threat'), ('PT ("Anxiety")', 'Potential Threat ("Anxiety")'), ('Sustained Threat', 'Sustained Threat'), ('Loss', 'Loss'), ('Frustrative Nonreward', 'Frustrative Nonreward'), ('Approach Motivation: Reward Valuation', 'Approach Motivation: Reward Valuation'), ('Approach Motivation: Effort Valuation / Willingness to Work', 'Approach Motivation: Effort Valuation / Willingness to Work'), ('Approach Motivation: Expectancy / Reward Prediction Error', 'Approach Motivation: Expectancy / Reward Prediction Error'), ('Approach Motivation: Action Selection / Preference-Based Decision Making', 'Approach Motivation: Action Selection / Preference-Based Decision Making'), ('Initial Responsiveness to Reward Attainment', 'Initial Responsiveness to Reward Attainment'), ('Sustained/Longer-Term Responsiveness to Reward Attainment', 'Sustained/Longer-Term Responsiveness to Reward Attainment'), ('Reward Learning', 'Reward Learning'), ('Habit', 'Habit'), ('Attention', 'Attention'), ('Perception', 'Perception'), ('Declarative Memory', 'Declarative Memory'), ('Language', 'Language'), ('Cognitive Control', 'Cognitive Control'), ('Working Memory', 'Working Memory'), ('Affiliation and Attachment', 'Affiliation and Attachment'), ('Social Communication', 'Social Communication'), ('Perception and Understanding of Self: Agency', 'Perception and Understanding of Self: Agency'), ('Perception and Understanding of Self: Self-Knowledge', 'Perception and Understanding of Self: Self-Knowledge'), ('Perceptions and Understanding of Others: Animacy Perception', 'Perceptions and Understanding of Others: Animacy Perception'), ('Perceptions and Understanding of Others: Action Perception', 'Perceptions and Understanding of Others: Action Perception'), ('Perceptions and Understanding of Others: Understanding Mental States', 'Perceptions and Understanding of Others: Understanding Mental States'), ('Arousal', 'Arousal'), ('Circadian Rhythms', 'Circadian Rhythms'), ('Sleep-Wakefulness', 'Sleep-Wakefulness')], max_length=255),
        ),
    ]
